object Versions {
    const val kotlinVersion = "1.9.23"
    const val coreKtx = "1.13.0"
    const val compose = "1.6.6"
    const val composeMaterial3 = "1.3.0-alpha06"
    const val composeNavigation = "2.7.7"
    const val composeHiltNavigation = "1.2.0"
    const val composeCompiler = "1.5.12"
    const val hilt = "2.51"
    const val okHttp = "4.12.0"
    const val retrofit = "2.9.0"
    const val moshi = "1.15.1"
    const val room = "2.5.0"
    const val paging = "3.3.0"
}